<?php
/**
 * OrganizationResourceApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  Backend\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Organization API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: devs@example.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.6.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Backend\Client\Test\Api;

use \Backend\Client\Configuration;
use \Backend\Client\ApiException;
use \Backend\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * OrganizationResourceApiTest Class Doc Comment
 *
 * @category Class
 * @package  Backend\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class OrganizationResourceApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for create
     *
     * Create new Organization.
     *
     */
    public function testCreate()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getAll
     *
     * Get all organizations.
     *
     */
    public function testGetAll()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getById
     *
     * Get Organization by Id.
     *
     */
    public function testGetById()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getFilterByCountry
     *
     * Get organizations filter by country.
     *
     */
    public function testGetFilterByCountry()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
